name: Check

on:
  push:
    branches: [ main, feat/* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clippy
        run: cargo clippy -- -D warnings
